version: "3.9"

services: 
  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FoodOrdering
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 20
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always

  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: go
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      Port: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
